version: "3"
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysql
    discuz:
        depends_on:
            - db
        build: .
        ports:
            - "80:80"
        restart: always
#        links:
#            - db
